weather_widget.settings:
  type: config_object
  label: 'Weather Widget settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
    location:
      type: string
      label: 'Default Location'
